const complexRates = {
    "Gdansk": [
        { name: "Львів (Комплекс Польща)", price: 1000 }
    ],
    "Klaipeda": [
        { name: "Львів (Комплекс Литва)", price: 1200 }
    ]
};

const seaRates = {
    "Chicago": { end: "Klaipeda", Motorcycle: 600, Car: 1025, SUV: 1025, Pickup: 1450 },
    "Los Angeles": { end: "Klaipeda", Motorcycle: 750, Car: 1450, SUV: 1450, Pickup: 1875 },
    "Honolulu": { end: "Klaipeda", Motorcycle: 1600, Car: 2600, SUV: 2600, Pickup: 3300 },
    "Seattle": { end: "Klaipeda", Motorcycle: 1000, Car: 1775, SUV: 1775, Pickup: 2500 },
    "Toronto": { end: "Klaipeda", Motorcycle: 600, Car: 1025, SUV: 1025, Pickup: 1500 },
    "Anchorage": { end: "Klaipeda", Motorcycle: 0, Car: 0, SUV: 0, Pickup: 0 },
    "New York": { end: "Gdansk", Motorcycle: 790, Car: 790, SUV: 950, Pickup: 1425 },
    "Savannah": { end: "Gdansk", Motorcycle: 790, Car: 790, SUV: 950, Pickup: 1425 },
    "Houston": { end: "Gdansk", Motorcycle: 880, Car: 880, SUV: 1080, Pickup: 1550 }
};

const db = {
    copart: {
        "ABILENE": { port: "Houston", Car: 525 },
        "ALBUQUERQUE": { port: "Houston", Car: 775 },
        "AMARILLO": { port: "Houston", Car: 700 },
        "ANDREWS": { port: "Houston", Car: 600 },
        "AUSTIN": { port: "Houston", Car: 425 },
        "BATON ROUGE": { port: "Houston", Car: 525 },
        "CORPUS CHRISTI": { port: "Houston", Car: 450 },
        "CRASHEDTOYS DALLAS": { port: "Houston", Car: 450 },
        "DALLAS": { port: "Houston", Car: 450 },
        "DALLAS SOUTH": { port: "Houston", Car: 450 },
        "EL PASO": { port: "Houston", Car: 600 },
        "FAYETTEVILLE": { port: "Houston", Car: 650 },
        "FT. WORTH": { port: "Houston", Car: 450 },
        "GRENADA": { port: "Houston", Car: 650 },
        "HOUSTON": { port: "Houston", Car: 355 },
        "HOUSTON EAST": { port: "Houston", Car: 355 },
        "JACKSON": { port: "Houston", Car: 600 },
        "LITTLE ROCK": { port: "Houston", Car: 625 },
        "LONGVIEW": { port: "Houston", Car: 450 },
        "LUFKIN": { port: "Houston", Car: 450 },
        "MCALLEN": { port: "Houston", Car: 525 },
        "NEW ORLEANS": { port: "Houston", Car: 575 },
        "NORTH AUSTIN": { port: "Houston", Car: 500 },
        "OKLAHOMA CITY": { port: "Houston", Car: 575 },
        "SAN ANTONIO": { port: "Houston", Car: 475 },
        "SHREVEPORT": { port: "Houston", Car: 490 },
        "TULSA": { port: "Houston", Car: 650 },
        "WACO": { port: "Houston", Car: 500 },
        "WICHITA": { port: "Houston", Car: 725 },
        "AKRON": { port: "New York", Car: 610 },
        "BALTIMORE": { port: "New York", Car: 410 },
        "BALTIMORE EAST": { port: "New York", Car: 410 },
        "CHARLESTON": { port: "New York", Car: 680 },
        "CLEVELAND EAST": { port: "New York", Car: 640 },
        "CLEVELAND WEST": { port: "New York", Car: 635 },
        "COLUMBUS": { port: "New York", Car: 710 },
        "DAYTON": { port: "New York", Car: 780 },
        "FREDERICKSBURG": { port: "New York", Car: 545 },
        "HAMPTON": { port: "New York", Car: 540 },
        "RICHMOND": { port: "New York", Car: 515 },
        "RICHMOND EAST": { port: "New York", Car: 520 },
        "WASHINGTON DC": { port: "New York", Car: 460 },
        "ALBANY": { port: "New York", Car: 450 },
        "ALTOONA": { port: "New York", Car: 625 },
        "BUFFALO": { port: "New York", Car: 675 },
        "CANDIA": { port: "New York", Car: 575 },
        "CHAMBERSBURG": { port: "New York", Car: 525 },
        "EXETER": { port: "New York", Car: 525 },
        "FREETOWN": { port: "New York", Car: 550 },
        "GLASSBORO EAST": { port: "New York", Car: 375 },
        "GLASSBORO WEST": { port: "New York", Car: 375 },
        "HARRISBURG": { port: "New York", Car: 450 },
        "HARTFORD": { port: "New York", Car: 400 },
        "HARTFORD SPRINGFIELD": { port: "New York", Car: 425 },
        "LONG ISLAND": { port: "New York", Car: 425 },
        "LYMAN": { port: "New York", Car: 650 },
        "N. BOSTON-ROWLEY SUBLOT": { port: "New York", Car: 625 },
        "NEWBURGH": { port: "New York", Car: 400 },
        "NORTH BOSTON": { port: "New York", Car: 550 },
        "PHILADELPHIA": { port: "New York", Car: 375 },
        "PHILADELPHIA EAST-SUBLOT": { port: "New York", Car: 375 },
        "PITTSBURGH EAST": { port: "New York", Car: 575 },
        "PITTSBURGH NORTH": { port: "New York", Car: 625 },
        "PITTSBURGH SOUTH": { port: "New York", Car: 625 },
        "PITTSBURGH WEST": { port: "New York", Car: 625 },
        "ROCHESTER": { port: "New York", Car: 625 },
        "RUTLAND": { port: "New York", Car: 675 },
        "SCRANTON": { port: "New York", Car: 425 },
        "SEAFORD": { port: "New York", Car: 500 },
        "SOMERVILLE": { port: "New York", Car: 325 },
        "SOUTH BOSTON": { port: "New York", Car: 550 },
        "SYRACUSE": { port: "New York", Car: 500 },
        "TRENTON": { port: "New York", Car: 325 },
        "WEBSTER": { port: "New York", Car: 575 },
        "WEST WARREN": { port: "New York", Car: 550 },
        "WINDHAM": { port: "New York", Car: 650 },
        "YORK HAVEN": { port: "New York", Car: 450 },
        "ATLANTA EAST": { port: "Savannah", Car: 475 },
        "ATLANTA NORTH": { port: "Savannah", Car: 500 },
        "ATLANTA SOUTH": { port: "Savannah", Car: 475 },
        "ATLANTA WEST": { port: "Savannah", Car: 475 },
        "AUGUSTA": { port: "Savannah", Car: 450 },
        "BIRMINGHAM": { port: "Savannah", Car: 550 },
        "CARTERSVILLE": { port: "Savannah", Car: 475 },
        "CRASHEDTOYS ATLANTA": { port: "Savannah", Car: 450 },
        "DOTHAN": { port: "Savannah", Car: 550 },
        "EARLINGTON": { port: "Savannah", Car: 725 },
        "FAIRBURN": { port: "Savannah", Car: 450 },
        "JACKSONVILLE EAST": { port: "Savannah", Car: 400 },
        "JACKSONVILLE NORTH": { port: "Savannah", Car: 400 },
        "JACKSONVILLE WEST": { port: "Savannah", Car: 400 },
        "KANSAS CITY": { port: "Savannah", Car: 800 },
        "KNOXVILLE": { port: "Savannah", Car: 575 },
        "LEXINGTON EAST": { port: "Savannah", Car: 725 },
        "LEXINGTON WEST": { port: "Savannah", Car: 725 },
        "LOUISVILLE": { port: "Savannah", Car: 725 },
        "MACON": { port: "Savannah", Car: 425 },
        "MEMPHIS": { port: "Savannah", Car: 675 },
        "COLUMBIA (MO)": { port: "Savannah", Car: 800 },
        "MOBILE": { port: "Savannah", Car: 575 },
        "MOBILE SOUTH": { port: "Savannah", Car: 575 },
        "MONTGOMERY": { port: "Savannah", Car: 575 },
        "NASHVILLE": { port: "Savannah", Car: 575 },
        "NORTH CHARLESTON": { port: "Savannah", Car: 450 },
        "SAVANNAH": { port: "Savannah", Car: 300 },
        "SAVANNAH / VERTIA SUBLOT": { port: "Savannah", Car: 350 },
        "COLUMBIA (SC)": { port: "Savannah", Car: 450 },
        "SPARTANBURG": { port: "Savannah", Car: 475 },
        "SPRINGFIELD": { port: "Savannah", Car: 800 },
        "ST. LOUIS": { port: "Savannah", Car: 750 },
        "SOUTHERN ILLINOIS": { port: "Savannah", Car: 750 },
        "TALLAHASSEE": { port: "Savannah", Car: 500 },
        "TANNER": { port: "Savannah", Car: 600 },
        "TIFTON": { port: "Savannah", Car: 450 },
        "WALTON": { port: "Savannah", Car: 725 },
        "CHINA GROVE": { port: "Savannah", Car: 530 },
        "CONCORD": { port: "Savannah", Car: 505 },
        "DANVILLE": { port: "Savannah", Car: 510 },
        "GASTONIA": { port: "Savannah", Car: 490 },
        "LUMBERTON": { port: "Savannah", Car: 410 },
        "MEBANE": { port: "Savannah", Car: 545 },
        "MOCKSVILLE": { port: "Savannah", Car: 530 },
        "RALEIGH": { port: "Savannah", Car: 500 },
        "CLEWISTON": { port: "Savannah", Car: 525 },
        "FT. PIERCE": { port: "Savannah", Car: 525 },
        "MIAMI CENTRAL": { port: "Savannah", Car: 500 },
        "MIAMI NORTH": { port: "Savannah", Car: 550 },
        "MIAMI SOUTH": { port: "Savannah", Car: 550 },
        "OCALA": { port: "Savannah", Car: 500 },
        "ORLANDO": { port: "Savannah", Car: 500 },
        "ORLANDO NORTH": { port: "Savannah", Car: 500 },
        "ORLANDO SOUTH": { port: "Savannah", Car: 500 },
        "PUNTA GORDA": { port: "Savannah", Car: 525 },
        "PUNTA GORDA SOUTH": { port: "Savannah", Car: 525 },
        "TAMPA SOUTH": { port: "Savannah", Car: 500 },
        "TAMPA SOUTH - MULBERRY SUBLOT": { port: "Savannah", Car: 500 },
        "WEST PALM BEACH": { port: "Savannah", Car: 500 },
        "ANCHORAGE": { port: "Anchorage", Car: "Call" },
        "ILLINOIS": { port: "New York", Car: 775 },
        "APPLETON": { port: "New York", Car: 850 },
        "BISMARCK": { port: "New York", Car: 1500 },
        "CASPER": { port: "New York", Car: 1500 },
        "CASPER WEST": { port: "New York", Car: "Call" },
        "CEDAR RAPIDS": { port: "New York", Car: 900 },
        "CHICAGO NORTH": { port: "New York", Car: 775 },
        "CHICAGO SOUTH": { port: "New York", Car: 800 },
        "CICERO": { port: "New York", Car: 900 },
        "COLORADO SPRINGS": { port: "Houston", Car: 900 },
        "DAVENPORT - 169 SUBLOT": { port: "New York", Car: 975 },
        "DAVENPORT": { port: "New York", Car: 975 },
        "DENVER": { port: "Houston", Car: 875 },
        "DENVER CENTRAL": { port: "Houston", Car: 875 },
        "DENVER SOUTH": { port: "Houston", Car: 875 },
        "DES MOINES": { port: "New York", Car: 900 },
        "DETROIT": { port: "New York", Car: 800 },
        "DYER": { port: "New York", Car: 800 },
        "FLINT": { port: "New York", Car: 800 },
        "FORT WAYNE": { port: "New York", Car: 800 },
        "INDIANAPOLIS": { port: "New York", Car: 800 },
        "IONIA": { port: "New York", Car: 900 },
        "KINCHELOE": { port: "New York", Car: 1200 },
        "LANSING": { port: "New York", Car: 900 },
        "LINCOLN": { port: "New York", Car: 950 },
        "MADISON": { port: "New York", Car: 825 },
        "MADISON SOUTH": { port: "New York", Car: 825 },
        "MILWAUKEE": { port: "New York", Car: 825 },
        "MILWAUKEE NORTH": { port: "New York", Car: 950 },
        "MILWAUKEE SOUTH": { port: "New York", Car: 900 },
        "MINNEAPOLIS": { port: "New York", Car: 850 },
        "MINNEAPOLIS NORTH": { port: "New York", Car: 850 },
        "PEORIA": { port: "New York", Car: 850 },
        "RAPID CITY": { port: "New York", Car: 1200 },
        "SIKESTON": { port: "New York", Car: 900 },
        "ST. CLOUD": { port: "New York", Car: 850 },
        "WAYLAND": { port: "New York", Car: 850 },
        "WHEELING": { port: "New York", Car: 850 },
        "HONOLULU": { port: "Honolulu", Car: 300 },
        "KINDAQUICK TOWING LLC": { port: "Honolulu", Car: 2100 },
        "ADELANTO": { port: "Los Angeles", Car: 475 },
        "ADP TOWING MAUI": { port: "Los Angeles", Car: 400 },
        "ANTELOPE": { port: "Los Angeles", Car: 575 },
        "BAKERSFIELD": { port: "Los Angeles", Car: 550 },
        "CRASHEDTOYS SACRAMENTO": { port: "Los Angeles", Car: 550 },
        "FRESNO": { port: "Los Angeles", Car: 575 },
        "HAYWARD": { port: "Los Angeles", Car: 600 },
        "KENS TOWING HILO": { port: "Los Angeles", Car: 2300 },
        "LAS VEGAS": { port: "Los Angeles", Car: 500 },
        "LAS VEGAS WEST": { port: "Los Angeles", Car: 675 },
        "LONG BEACH": { port: "Los Angeles", Car: 350 },
        "LOS ANGELES": { port: "Los Angeles", Car: 360 },
        "MARTINEZ": { port: "Los Angeles", Car: 575 },
        "MENTONE": { port: "Los Angeles", Car: 475 },
        "NAPA": { port: "Los Angeles", Car: 750 },
        "OGDEN": { port: "Los Angeles", Car: 750 },
        "PHOENIX": { port: "Los Angeles", Car: 525 },
        "PHOENIX NORTH": { port: "Los Angeles", Car: 675 },
        "RANCHO CUCAMONGA": { port: "Los Angeles", Car: 400 },
        "REDDING": { port: "Los Angeles", Car: 975 },
        "RENO": { port: "Los Angeles", Car: 725 },
        "SACRAMENTO": { port: "Los Angeles", Car: 575 },
        "SALT LAKE CITY": { port: "Los Angeles", Car: 825 },
        "SALT LAKE CITY NORTH": { port: "Los Angeles", Car: 725 },
        "SAN BERNARDINO": { port: "Los Angeles", Car: 400 },
        "SAN DIEGO": { port: "Los Angeles", Car: 500 },
        "SAN JOSE": { port: "Los Angeles", Car: 575 },
        "SO SACRAMENTO": { port: "Los Angeles", Car: 575 },
        "SUN VALLEY": { port: "Los Angeles", Car: 400 },
        "TOW GUYS KAMUELA": { port: "Los Angeles", Car: 2550 },
        "TUCSON": { port: "Los Angeles", Car: 575 },
        "VALLEJO": { port: "Los Angeles", Car: 575 },
        "VAN NUYS": { port: "Los Angeles", Car: 375 },
        "BILLINGS": { port: "Seattle", Car: 1100 },
        "BOISE": { port: "Seattle", Car: 700 },
        "EUGENE": { port: "Seattle", Car: 600 },
        "GRAHAM": { port: "Seattle", Car: 450 },
        "HELENA": { port: "Seattle", Car: 1000 },
        "NORTH SEATTLE": { port: "Seattle", Car: 475 },
        "PASCO": { port: "Seattle", Car: 600 },
        "PORTLAND NORTH": { port: "Seattle", Car: 500 },
        "PORTLAND SOUTH": { port: "Seattle", Car: 550 },
        "SPOKANE": { port: "Seattle", Car: 600 }
    },
    iaai: {
        "NEW ORLEANS EAST": { port: "Houston", Car: 600 },
        "ABILENE": { port: "Houston", Car: 525 },
        "ALBUQUERQUE": { port: "Houston", Car: 775 },
        "AMARILLO": { port: "Houston", Car: 700 },
        "AUSTIN": { port: "Houston", Car: 450 },
        "AUSTIN NORTH": { port: "Houston", Car: 475 },
        "BATON ROUGE": { port: "Houston", Car: 550 },
        "CORPUS CHRISTI": { port: "Houston", Car: 425 },
        "DALLAS": { port: "Houston", Car: 450 },
        "DALLAS/FT WORTH": { port: "Houston", Car: 450 },
        "EL PASO": { port: "Houston", Car: 600 },
        "FAYETTEVILLE": { port: "Houston", Car: 675 },
        "FORT WORTH NORTH": { port: "Houston", Car: 475 },
        "GRENADA": { port: "Houston", Car: 650 },
        "GULF COAST": { port: "Houston", Car: 650 },
        "HOUSTON": { port: "Houston", Car: 400 },
        "HOUSTON SOUTH": { port: "Houston", Car: 400 },
        "HOUSTON-NORTH": { port: "Houston", Car: 390 },
        "JACKSON": { port: "Houston", Car: 600 },
        "LAFAYETTE": { port: "Houston", Car: 450 },
        "LITTLE ROCK": { port: "Houston", Car: 650 },
        "LONGVIEW": { port: "Houston", Car: 450 },
        "LUBBOCK": { port: "Houston", Car: 650 },
        "MCALLEN": { port: "Houston", Car: 525 },
        "NEW ORLEANS": { port: "Houston", Car: 575 },
        "OKLAHOMA CITY": { port: "Houston", Car: 575 },
        "PERMIAN BASIN": { port: "Houston", Car: 650 },
        "SAN ANTONIO": { port: "Houston", Car: 500 },
        "SAN ANTONIO-SOUTH": { port: "Houston", Car: 500 },
        "SHREVEPORT": { port: "Houston", Car: 500 },
        "TULSA": { port: "Houston", Car: 675 },
        "WICHITA": { port: "Houston", Car: 725 },
        "ALBANY": { port: "New York", Car: 475 },
        "ALTOONA": { port: "New York", Car: 625 },
        "AVENEL NEW JERSEY": { port: "New York", Car: 300 },
        "BOSTON - SHIRLEY": { port: "New York", Car: 550 },
        "BRIDGEPORT": { port: "New York", Car: 375 },
        "BUFFALO": { port: "New York", Car: 675 },
        "BURLINGTON": { port: "New York", Car: 675 },
        "CENTRAL NEW JERSEY": { port: "New York", Car: 350 },
        "ERIE": { port: "New York", Car: 675 },
        "ENGLISHTOWN": { port: "New York", Car: 350 },
        "HARTFORD": { port: "New York", Car: 400 },
        "HARTFORD-SOUTH": { port: "New York", Car: 400 },
        "LONG ISLAND": { port: "New York", Car: 425 },
        "MANCHESTER": { port: "New York", Car: 575 },
        "NEW CASTLE": { port: "New York", Car: 425 },
        "NEWBURGH": { port: "New York", Car: 400 },
        "NORTHERN NEW JERSEY": { port: "New York", Car: 300 },
        "PHILADELPHIA": { port: "New York", Car: 375 },
        "PITTSBURGH": { port: "New York", Car: 625 },
        "PITTSBURGH-NORTH": { port: "New York", Car: 625 },
        "PORT MURRAY": { port: "New York", Car: 375 },
        "PORTLAND - GORHAM": { port: "New York", Car: 650 },
        "PROVIDENCE": { port: "New York", Car: 525 },
        "PHILADELPHIA EAST": { port: "New York", Car: 375 },
        "ROCHESTER": { port: "New York", Car: 650 },
        "SCRANTON": { port: "New York", Car: 450 },
        "SOUTHERN NEW JERSEY": { port: "New York", Car: 375 },
        "SYRACUSE": { port: "New York", Car: 500 },
        "SAYREVILLE": { port: "New York", Car: 350 },
        "TAUNTON": { port: "New York", Car: 550 },
        "TEMPLETON": { port: "New York", Car: 550 },
        "YORK SPRINGS": { port: "New York", Car: 450 },
        "AKRON-CANTON": { port: "New York", Car: 650 },
        "BALTIMORE": { port: "New York", Car: 400 },
        "BUCKHANNON": { port: "New York", Car: 600 },
        "CINCINNATI": { port: "New York", Car: 825 },
        "CINCINNATI SOUTH": { port: "New York", Car: 825 },
        "CLEVELAND": { port: "New York", Car: 750 },
        "COLUMBUS": { port: "New York", Car: 700 },
        "CULPEPER": { port: "New York", Car: 600 },
        "DAYTON": { port: "New York", Car: 815 },
        "DUNDALK": { port: "New York", Car: 400 },
        "ELKTON": { port: "New York", Car: 400 },
        "FREDERICKSBURG-SOUTH": { port: "New York", Car: 580 },
        "LAUREL": { port: "New York", Car: 450 },
        "METRO DC": { port: "New York", Car: 450 },
        "NORTHERN VIRGINIA": { port: "New York", Car: 550 },
        "RICHMOND": { port: "New York", Car: 545 },
        "ROANOKE": { port: "New York", Car: 600 },
        "ROSEDALE": { port: "New York", Car: 450 },
        "SHADY SPRING": { port: "New York", Car: 585 },
        "TIDEWATER": { port: "New York", Car: 565 },
        "ASHEVILLE": { port: "Savannah", Car: 550 },
        "CHARLOTTE": { port: "Savannah", Car: 500 },
        "CONCORD": { port: "Savannah", Car: 500 },
        "GREENSBORO": { port: "Savannah", Car: 500 },
        "HIGH POINT": { port: "Savannah", Car: 500 },
        "PULASKI": { port: "Savannah", Car: 500 },
        "RALEIGH": { port: "Savannah", Car: 500 },
        "SUFFOLK": { port: "Savannah", Car: 550 },
        "WILMINGTON": { port: "Savannah", Car: 500 },
        "ATLANTA": { port: "Savannah", Car: 475 },
        "ATLANTA EAST": { port: "Savannah", Car: 500 },
        "ATLANTA NORTH": { port: "Savannah", Car: 475 },
        "ATLANTA SOUTH": { port: "Savannah", Car: 475 },
        "BIRMINGHAM": { port: "Savannah", Car: 550 },
        "CHARLESTON": { port: "Savannah", Car: 475 },
        "CHATTANOOGA": { port: "Savannah", Car: 650 },
        "COLUMBIA": { port: "Savannah", Car: 450 },
        "DOTHAN": { port: "Savannah", Car: 550 },
        "GREENVILLE": { port: "Savannah", Car: 475 },
        "HUNTSVILLE": { port: "Savannah", Car: 650 },
        "INDIANAPOLIS SOUTH": { port: "Savannah", Car: 775 },
        "JACKSONVILLE": { port: "Savannah", Car: 400 },
        "KANSAS CITY": { port: "Savannah", Car: 800 },
        "KNOXVILLE": { port: "Savannah", Car: 575 },
        "KANSAS CITY EAST": { port: "Savannah", Car: 800 },
        "LOUISVILLE": { port: "Savannah", Car: 750 },
        "LOUISVILLE NORTH": { port: "Savannah", Car: 750 },
        "LEXINGTON": { port: "Savannah", Car: 500 },
        "MACON": { port: "Savannah", Car: 475 },
        "MEMPHIS": { port: "Savannah", Car: 700 },
        "NASHVILLE": { port: "Savannah", Car: 575 },
        "NEW ORLEANS AND LOUISIANA FLOOD": { port: "Savannah", Car: 600 },
        "SAVANNAH": { port: "Savannah", Car: 325 },
        "SPRINGFIELD": { port: "Savannah", Car: 800 },
        "ST. LOUIS": { port: "Savannah", Car: 750 },
        "TIFTON": { port: "Savannah", Car: 475 },
        "FORT MYERS": { port: "Savannah", Car: 550 },
        "FORT PIERCE": { port: "Savannah", Car: 550 },
        "MIAMI": { port: "Savannah", Car: 550 },
        "MIAMI-NORTH": { port: "Savannah", Car: 550 },
        "ORLANDO": { port: "Savannah", Car: 500 },
        "ORLANDO-NORTH": { port: "Savannah", Car: 500 },
        "PENSACOLA": { port: "Savannah", Car: 550 },
        "TAMPA": { port: "Savannah", Car: 500 },
        "TAMPA NORTH": { port: "Savannah", Car: 500 },
        "WEST PALM BEACH": { port: "Savannah", Car: 550 },
        "ANCHORAGE": { port: "Anchorage", Car: "Call" },
        "APPLETON": { port: "New York", Car: 875 },
        "CHICAGO-NORTH": { port: "New York", Car: 775 },
        "CHICAGO-SOUTH": { port: "New York", Car: 775 },
        "CHICAGO-WEST": { port: "New York", Car: 775 },
        "COLORADO SPRINGS": { port: "Houston", Car: 800 },
        "DAVENPORT": { port: "New York", Car: 850 },
        "DENVER": { port: "Houston", Car: 850 },
        "DENVER EAST": { port: "Houston", Car: 850 },
        "DES MOINES": { port: "New York", Car: 900 },
        "DETROIT": { port: "New York", Car: 800 },
        "FARGO": { port: "New York", Car: 1300 },
        "FLINT": { port: "New York", Car: 800 },
        "FORT WAYNE": { port: "New York", Car: 800 },
        "GRAND RAPIDS": { port: "New York", Car: 800 },
        "INDIANAPOLIS": { port: "New York", Car: 800 },
        "LINCOLN": { port: "New York", Car: 900 },
        "MILWAUKEE": { port: "New York", Car: 850 },
        "MINNEAPOLIS/ST. PAUL": { port: "New York", Car: 850 },
        "MINNEAPOLIS SOUTH": { port: "New York", Car: 850 },
        "OMAHA": { port: "New York", Car: 950 },
        "OMAHA SOUTH": { port: "New York", Car: 950 },
        "PORTAGE": { port: "New York", Car: 800 },
        "SIOUX FALLS": { port: "New York", Car: 1250 },
        "SOUTH BEND": { port: "New York", Car: 800 },
        "ST. CLOUD": { port: "New York", Car: 900 },
        "HONOLULU": { port: "Honolulu", Car: 325 },
        "LEE'S TOWING KAUAI (HONOLULU)": { port: "Honolulu", Car: 2000 },
        "ACE - CARSON": { port: "Los Angeles", Car: 350 },
        "ACE - PERRIS 2": { port: "Los Angeles", Car: 475 },
        "ACE - PERRIS": { port: "Los Angeles", Car: 450 },
        "ANAHEIM": { port: "Los Angeles", Car: 375 },
        "BZ TRUCKING": { port: "Los Angeles", Car: 2500 },
        "COLTON": { port: "Los Angeles", Car: 400 },
        "D&D TOWING INC MAUI": { port: "Los Angeles", Car: 2700 },
        "DC TOWING HILO": { port: "Los Angeles", Car: 2450 },
        "EAST BAY": { port: "Los Angeles", Car: 600 },
        "FONTANA": { port: "Los Angeles", Car: 400 },
        "FREMONT": { port: "Los Angeles", Car: 600 },
        "FRESNO": { port: "Los Angeles", Car: 575 },
        "HIGH DESERT": { port: "Los Angeles", Car: 500 },
        "LAS VEGAS - (OLD)": { port: "Los Angeles", Car: 500 },
        "LAS VEGAS": { port: "Los Angeles", Car: 550 },
        "LEE'S TOWING KAUAI (LA)": { port: "Los Angeles", Car: 3000 },
        "LOS ANGELES": { port: "Los Angeles", Car: 375 },
        "LOS ANGELES SOUTH": { port: "Los Angeles", Car: 350 },
        "NORTH HOLLYWOOD": { port: "Los Angeles", Car: 400 },
        "PHOENIX": { port: "Los Angeles", Car: 550 },
        "PROVO": { port: "Los Angeles", Car: 825 },
        "RENO": { port: "Los Angeles", Car: 725 },
        "SACRAMENTO": { port: "Los Angeles", Car: 575 },
        "SALT LAKE CITY": { port: "Los Angeles", Car: 750 },
        "SAN BERNARDINO": { port: "Los Angeles", Car: 450 },
        "SAN DIEGO": { port: "Los Angeles", Car: 475 },
        "SANTA CLARITA": { port: "Los Angeles", Car: 475 },
        "STOCKTON": { port: "Los Angeles", Car: 650 },
        "TUCSON": { port: "Los Angeles", Car: 600 },
        "BILLINGS": { port: "Seattle", Car: 1100 },
        "BOISE": { port: "Seattle", Car: 700 },
        "EUGENE": { port: "Seattle", Car: 600 },
        "MISSOULA": { port: "Seattle", Car: 850 },
        "PORTLAND": { port: "Seattle", Car: 500 },
        "PORTLAND SOUTH": { port: "Seattle", Car: 550 },
        "PORTLAND WEST": { port: "Seattle", Car: 500 },
        "SEATTLE": { port: "Seattle", Car: 650 },
        "SPOKANE": { port: "Seattle", Car: 600 }
    },
    canada: {
        "CALGARY": { port: "Toronto", Car: 1750, tax: 0.05 },
        "EDMONTON": { port: "Toronto", Car: 1750, tax: 0.05 },
        "HALIFAX": { port: "Toronto", Car: 1500, tax: 0.15 },
        "LONDON": { port: "Toronto", Car: 450, tax: 0.13 },
        "MONCTON": { port: "Toronto", Car: 1600, tax: 0.15 },
        "MONTREAL": { port: "Toronto", Car: 800, tax: 0.05 },
        "OTTAWA": { port: "Toronto", Car: 750, tax: 0.13 },
        "ST. JOHN'S": { port: "Toronto", Car: 2100, tax: 0.15 },
        "TORONTO": { port: "Toronto", Car: 450, tax: 0.13 }
    }
};